### ISSUE TITLE
Error running classification.py

### ISSUE THREAD

**Issue by gvrkiran** [yuhaodu/TwitterMeme#1]
AttributeError: module 'MemeModel' has no attribute 'MemeClassifier'

I guess it is Meme_classifier? But if I change that, I get the error: 

  File "classification.py", line 53, in <module>
    model = mm.Meme_classifier(backbone,matrix)
TypeError: __init__() missing 3 required positional arguments: 'hidden_size2', 'hidden_size', and 'batch_size'

**Comment by yuhaodu** [comment]
Updated! Let me if you have more problems.
